version: 2

builds:
- goos:
    - linux
    - windows
    - darwin
  goarch:
    - amd64
    - arm64
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      formats: [zip]
    files:
      - README.md
      - LICENSE
